/*
 * EEZ Modular Firmware
 * Copyright (C) 2021-present, Envox d.o.o.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <stdint.h>

#if defined(EEZ_PLATFORM_STM32)
#if CONF_OPTION_FPGA
static const uint32_t DISPLAY_WIDTH = 800;
static const uint32_t DISPLAY_HEIGHT = 480;
#else
static const uint32_t DISPLAY_WIDTH = 480;
static const uint32_t DISPLAY_HEIGHT = 272;
#endif
static const uint32_t DISPLAY_BPP = 16; // RGB565
#endif

#if defined(EEZ_PLATFORM_SIMULATOR)
static const uint32_t DISPLAY_WIDTH = 1396;
static const uint32_t DISPLAY_HEIGHT = 563;
static const uint32_t DISPLAY_BPP = 32;  // RGBA8888

static const char *TITLE = "BB3 Firmware Simulator";
static const char *ICON = "eez.png";
#endif

#define MAX_NUM_OF_Y_AXES 18
#define MAX_NUM_OF_Y_VALUES MAX_NUM_OF_Y_AXES

#define OPTION_KEYBOARD 1
#define OPTION_MOUSE 1

#define CUSTOM_VALUE_TYPES \
    VALUE_TYPE(PASSWORD) \
    VALUE_TYPE(PERCENTAGE) \
    VALUE_TYPE(SIZE) \
    VALUE_TYPE(TIME_SECONDS) \
    VALUE_TYPE(LESS_THEN_MIN_FLOAT) \
    VALUE_TYPE(GREATER_THEN_MAX_FLOAT) \
    VALUE_TYPE(CHANNEL_LABEL) \
    VALUE_TYPE(CHANNEL_SHORT_LABEL) \
    VALUE_TYPE(CHANNEL_SHORT_LABEL_WITHOUT_COLUMN) \
    VALUE_TYPE(CHANNEL_BOARD_INFO_LABEL) \
    VALUE_TYPE(LESS_THEN_MIN_INT) \
    VALUE_TYPE(LESS_THEN_MIN_TIME_ZONE) \
    VALUE_TYPE(GREATER_THEN_MAX_INT) \
    VALUE_TYPE(GREATER_THEN_MAX_TIME_ZONE) \
    VALUE_TYPE(EVENT) \
    VALUE_TYPE(EVENT_MESSAGE) \
    VALUE_TYPE(ON_TIME_COUNTER) \
    VALUE_TYPE(COUNTDOWN) \
    VALUE_TYPE(DATE_DMY) \
    VALUE_TYPE(DATE_MDY) \
    VALUE_TYPE(YEAR) \
    VALUE_TYPE(MONTH) \
    VALUE_TYPE(DAY) \
    VALUE_TYPE(TIME) \
    VALUE_TYPE(TIME12) \
    VALUE_TYPE(HOUR) \
    VALUE_TYPE(MINUTE) \
    VALUE_TYPE(SECOND) \
    VALUE_TYPE(USER_PROFILE_LABEL) \
    VALUE_TYPE(USER_PROFILE_REMARK) \
    VALUE_TYPE(EDIT_INFO) \
    VALUE_TYPE(MAC_ADDRESS) \
    VALUE_TYPE(PORT) \
    VALUE_TYPE(TEXT_MESSAGE) \
    VALUE_TYPE(STEP_VALUES) \
    VALUE_TYPE(FLOAT_LIST) \
    VALUE_TYPE(CHANNEL_TITLE) \
    VALUE_TYPE(CHANNEL_SHORT_TITLE) \
    VALUE_TYPE(CHANNEL_SHORT_TITLE_WITHOUT_TRACKING_ICON) \
    VALUE_TYPE(CHANNEL_LONG_TITLE) \
    VALUE_TYPE(CHANNEL_ID) \
    VALUE_TYPE(DLOG_VALUE_LABEL) \
    VALUE_TYPE(DLOG_CURRENT_TIME) \
    VALUE_TYPE(FILE_LENGTH) \
    VALUE_TYPE(FILE_DATE_TIME) \
    VALUE_TYPE(FIRMWARE_VERSION) \
    VALUE_TYPE(SLOT_INDEX) \
    VALUE_TYPE(SLOT_INFO) \
    VALUE_TYPE(SLOT_INFO_WITH_FW_VER) \
    VALUE_TYPE(SLOT_TITLE) \
    VALUE_TYPE(SLOT_TITLE_DEF) \
    VALUE_TYPE(SLOT_TITLE_MAX) \
    VALUE_TYPE(SLOT_TITLE_SETTINGS) \
    VALUE_TYPE(SLOT_SHORT_TITLE) \
    VALUE_TYPE(MASTER_INFO) \
    VALUE_TYPE(MASTER_INFO_WITH_FW_VER) \
    VALUE_TYPE(TEST_RESULT) \
    VALUE_TYPE(SCPI_ERROR) \
    VALUE_TYPE(STORAGE_INFO) \
    VALUE_TYPE(FOLDER_INFO) \
    VALUE_TYPE(MODULE_SERIAL_INFO) \
    VALUE_TYPE(CALIBRATION_VALUE_TYPE_INFO) \
    VALUE_TYPE(CALIBRATION_POINT_INFO) \
    VALUE_TYPE(ZOOM) \
    VALUE_TYPE(NUM_SELECTED) \
	VALUE_TYPE(CURRENT_DIRECTORY_TITLE) \
	VALUE_TYPE(MASS_STORAGE_DEVICE_LABEL) \
	VALUE_TYPE(OCP_TRIP_LEVEL_INFO) \
	VALUE_TYPE(AUTO_START_SCRIPT_CONFIRMATION_MESSAGE) \

#define DISPLAY_BACKGROUND_LUMINOSITY_STEP_MIN 0
#define DISPLAY_BACKGROUND_LUMINOSITY_STEP_MAX 20
#define DISPLAY_BACKGROUND_LUMINOSITY_STEP_DEFAULT 10

#define UTF8_SUPPORT 0