/*
* EEZ Generic Firmware
* Copyright (C) 2021-present, Envox d.o.o.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.

* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.

* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

namespace eez {
namespace flow {
namespace defs_v3 {

enum ComponentTypes {
    COMPONENT_TYPE_NONE = 0,
    COMPONENT_TYPE_CONTAINER_WIDGET = 1,
    COMPONENT_TYPE_LIST_WIDGET = 2,
    COMPONENT_TYPE_GRID_WIDGET = 3,
    COMPONENT_TYPE_SELECT_WIDGET = 4,
    COMPONENT_TYPE_DISPLAY_DATA_WIDGET = 5,
    COMPONENT_TYPE_TEXT_WIDGET = 6,
    COMPONENT_TYPE_MULTILINE_TEXT_WIDGET = 7,
    COMPONENT_TYPE_RECTANGLE_WIDGET = 8,
    COMPONENT_TYPE_BITMAP_WIDGET = 9,
    COMPONENT_TYPE_BUTTON_WIDGET = 10,
    COMPONENT_TYPE_TOGGLE_BUTTON_WIDGET = 11,
    COMPONENT_TYPE_BUTTON_GROUP_WIDGET = 12,
    COMPONENT_TYPE_BAR_GRAPH_WIDGET = 14,
    COMPONENT_TYPE_LAYOUT_VIEW_WIDGET = 15,
    COMPONENT_TYPE_YTGRAPH_WIDGET = 16,
    COMPONENT_TYPE_UP_DOWN_WIDGET = 17,
    COMPONENT_TYPE_LIST_GRAPH_WIDGET = 18,
    COMPONENT_TYPE_APP_VIEW_WIDGET = 19,
    COMPONENT_TYPE_SCROLL_BAR_WIDGET = 20,
    COMPONENT_TYPE_PROGRESS_WIDGET = 21,
    COMPONENT_TYPE_CANVAS_WIDGET = 22,
    COMPONENT_TYPE_START_ACTION = 1001,
    COMPONENT_TYPE_END_ACTION = 1002,
    COMPONENT_TYPE_INPUT_ACTION = 1003,
    COMPONENT_TYPE_OUTPUT_ACTION = 1004,
    COMPONENT_TYPE_GET_VARIABLE_ACTION = 1005,
    COMPONENT_TYPE_EVAL_ACTION = 1006,
    COMPONENT_TYPE_SET_VARIABLE_ACTION = 1007,
    COMPONENT_TYPE_DECLARE_VARIABLE_ACTION = 1008,
    COMPONENT_TYPE_COMPARE_ACTION = 1009,
    COMPONENT_TYPE_IS_TRUE_ACTION = 1010,
    COMPONENT_TYPE_CONSTANT_ACTION = 1011,
    COMPONENT_TYPE_DATE_NOW_ACTION = 1012,
    COMPONENT_TYPE_READ_SETTING_ACTION = 1013,
    COMPONENT_TYPE_WRITE_SETTINGS_ACTION = 1014,
    COMPONENT_TYPE_LOG_ACTION = 1015,
    COMPONENT_TYPE_CALL_ACTION_ACTION = 1016,
    COMPONENT_TYPE_COMMENT_ACTION = 1017,
    COMPONENT_TYPE_DELAY_ACTION = 1018,
    COMPONENT_TYPE_ERROR_ACTION = 1019,
    COMPONENT_TYPE_CATCH_ERROR_ACTION = 1020,
    COMPONENT_TYPE_COUNTER_ACTION = 1021,
    COMPONENT_TYPE_SHOW_PAGE_ACTION = 1022,
    COMPONENT_TYPE_SCPI_ACTION = 1023
};

enum Component_CONTAINER_WIDGET_Inputs {
    CONTAINER_WIDGET_INPUT_DATA = 1,
    CONTAINER_WIDGET_INPUT_OVERLAY = 2,
    CONTAINER_WIDGET_INPUT_VISIBLE = 3
};

enum Component_LIST_WIDGET_Inputs {
    LIST_WIDGET_INPUT_DATA = 1
};

enum Component_GRID_WIDGET_Inputs {
    GRID_WIDGET_INPUT_DATA = 1
};

enum Component_SELECT_WIDGET_Inputs {
    SELECT_WIDGET_INPUT_DATA = 1
};

enum Component_DISPLAY_DATA_WIDGET_Inputs {
    DISPLAY_DATA_WIDGET_INPUT_DATA = 1
};

enum Component_TEXT_WIDGET_Inputs {
    TEXT_WIDGET_INPUT_DATA = 1
};

enum Component_MULTILINE_TEXT_WIDGET_Inputs {
    MULTILINE_TEXT_WIDGET_INPUT_DATA = 1
};

enum Component_RECTANGLE_WIDGET_Inputs {
    RECTANGLE_WIDGET_INPUT_DATA = 1
};

enum Component_BITMAP_WIDGET_Inputs {
    BITMAP_WIDGET_INPUT_DATA = 1
};

enum Component_BUTTON_WIDGET_Inputs {
    BUTTON_WIDGET_INPUT_DATA = 1,
    BUTTON_WIDGET_INPUT_ENABLED = 2
};

enum Component_TOGGLE_BUTTON_WIDGET_Inputs {
    TOGGLE_BUTTON_WIDGET_INPUT_DATA = 1
};

enum Component_BUTTON_GROUP_WIDGET_Inputs {
    BUTTON_GROUP_WIDGET_INPUT_DATA = 1
};

enum Component_BAR_GRAPH_WIDGET_Inputs {
    BAR_GRAPH_WIDGET_INPUT_DATA = 1,
    BAR_GRAPH_WIDGET_INPUT_LINE1_DATA = 2,
    BAR_GRAPH_WIDGET_INPUT_LINE2_DATA = 3
};

enum Component_LAYOUT_VIEW_WIDGET_Inputs {
    LAYOUT_VIEW_WIDGET_INPUT_DATA = 1,
    LAYOUT_VIEW_WIDGET_INPUT_CONTEXT = 2,
    LAYOUT_VIEW_WIDGET_INPUT_VISIBLE = 3
};

enum Component_YTGRAPH_WIDGET_Inputs {
    YTGRAPH_WIDGET_INPUT_DATA = 1,
    YTGRAPH_WIDGET_INPUT_Y2_DATA = 2
};

enum Component_UP_DOWN_WIDGET_Inputs {
    UP_DOWN_WIDGET_INPUT_DATA = 1
};

enum Component_LIST_GRAPH_WIDGET_Inputs {
    LIST_GRAPH_WIDGET_INPUT_DATA = 1,
    LIST_GRAPH_WIDGET_INPUT_DWELL_DATA = 2,
    LIST_GRAPH_WIDGET_INPUT_Y1_DATA = 3,
    LIST_GRAPH_WIDGET_INPUT_Y2_DATA = 4,
    LIST_GRAPH_WIDGET_INPUT_CURSOR_DATA = 5
};

enum Component_APP_VIEW_WIDGET_Inputs {
    APP_VIEW_WIDGET_INPUT_DATA = 1
};

enum Component_SCROLL_BAR_WIDGET_Inputs {
    SCROLL_BAR_WIDGET_INPUT_DATA = 1
};

enum Component_PROGRESS_WIDGET_Inputs {
    PROGRESS_WIDGET_INPUT_DATA = 1
};

enum Component_CANVAS_WIDGET_Inputs {
    CANVAS_WIDGET_INPUT_DATA = 1
};

enum Component_SET_VARIABLE_ACTION_COMPONENT_Inputs {
    SET_VARIABLE_ACTION_COMPONENT_INPUT_VALUE = 1
};

enum Component_DECLARE_VARIABLE_ACTION_COMPONENT_Inputs {
    DECLARE_VARIABLE_ACTION_COMPONENT_INPUT_VALUE = 1
};

enum Component_COMPARE_ACTION_COMPONENT_Inputs {
    COMPARE_ACTION_COMPONENT_INPUT_A = 1,
    COMPARE_ACTION_COMPONENT_INPUT_B = 2,
    COMPARE_ACTION_COMPONENT_INPUT_C = 3
};

enum Component_IS_TRUE_ACTION_COMPONENT_Inputs {
    IS_TRUE_ACTION_COMPONENT_INPUT_VALUE = 1
};

enum Component_READ_SETTING_ACTION_COMPONENT_Inputs {
    READ_SETTING_ACTION_COMPONENT_INPUT_KEY = 1
};

enum Component_WRITE_SETTINGS_ACTION_COMPONENT_Inputs {
    WRITE_SETTINGS_ACTION_COMPONENT_INPUT_KEY = 1
};

enum Component_CALL_ACTION_ACTION_COMPONENT_Inputs {
    CALL_ACTION_ACTION_COMPONENT_INPUT_ACTION = 1
};

enum Component_DELAY_ACTION_COMPONENT_Inputs {
    DELAY_ACTION_COMPONENT_INPUT_MILLISECONDS = 1
};

enum Component_ERROR_ACTION_COMPONENT_Inputs {
    ERROR_ACTION_COMPONENT_INPUT_MESSAGE = 1
};

enum Component_SCPI_ACTION_COMPONENT_Inputs {
    SCPI_ACTION_COMPONENT_INPUT_INSTRUMENT = 1
};

enum Component_CONTAINER_WIDGET_Outputs {
    CONTAINER_WIDGET_OUTPUT_ACTION = 1
};

enum Component_LIST_WIDGET_Outputs {
    LIST_WIDGET_OUTPUT_ACTION = 1
};

enum Component_GRID_WIDGET_Outputs {
    GRID_WIDGET_OUTPUT_ACTION = 1
};

enum Component_SELECT_WIDGET_Outputs {
    SELECT_WIDGET_OUTPUT_ACTION = 1
};

enum Component_DISPLAY_DATA_WIDGET_Outputs {
    DISPLAY_DATA_WIDGET_OUTPUT_ACTION = 1
};

enum Component_TEXT_WIDGET_Outputs {
    TEXT_WIDGET_OUTPUT_ACTION = 1
};

enum Component_MULTILINE_TEXT_WIDGET_Outputs {
    MULTILINE_TEXT_WIDGET_OUTPUT_ACTION = 1
};

enum Component_RECTANGLE_WIDGET_Outputs {
    RECTANGLE_WIDGET_OUTPUT_ACTION = 1
};

enum Component_BITMAP_WIDGET_Outputs {
    BITMAP_WIDGET_OUTPUT_ACTION = 1
};

enum Component_BUTTON_WIDGET_Outputs {
    BUTTON_WIDGET_OUTPUT_ACTION = 1
};

enum Component_TOGGLE_BUTTON_WIDGET_Outputs {
    TOGGLE_BUTTON_WIDGET_OUTPUT_ACTION = 1
};

enum Component_BUTTON_GROUP_WIDGET_Outputs {
    BUTTON_GROUP_WIDGET_OUTPUT_ACTION = 1
};

enum Component_BAR_GRAPH_WIDGET_Outputs {
    BAR_GRAPH_WIDGET_OUTPUT_ACTION = 1
};

enum Component_LAYOUT_VIEW_WIDGET_Outputs {
    LAYOUT_VIEW_WIDGET_OUTPUT_ACTION = 1
};

enum Component_YTGRAPH_WIDGET_Outputs {
    YTGRAPH_WIDGET_OUTPUT_ACTION = 1
};

enum Component_UP_DOWN_WIDGET_Outputs {
    UP_DOWN_WIDGET_OUTPUT_ACTION = 1
};

enum Component_LIST_GRAPH_WIDGET_Outputs {
    LIST_GRAPH_WIDGET_OUTPUT_ACTION = 1
};

enum Component_APP_VIEW_WIDGET_Outputs {
    APP_VIEW_WIDGET_OUTPUT_ACTION = 1
};

enum Component_SCROLL_BAR_WIDGET_Outputs {
    SCROLL_BAR_WIDGET_OUTPUT_ACTION = 1
};

enum Component_PROGRESS_WIDGET_Outputs {
    PROGRESS_WIDGET_OUTPUT_ACTION = 1
};

enum Component_CANVAS_WIDGET_Outputs {
    CANVAS_WIDGET_OUTPUT_ACTION = 1
};

} // defs_v3
} // flow
} // eez